### ISSUE TITLE
Live train is not following the metro line path, would make it more cool

### ISSUE THREAD

**Issue by subins2000** [amith-vp/kochi-metro-timings#1]
![Screenshot_20241030_111706](https://github.com/user-attachments/assets/bbc2970e-03b9-411f-9633-0221c10ecfa2)

**Comment by amith-vp** [comment]
Currently, first the train progress is calculated using its arrival and departure times between two stations. 

The trains lat & lon are then interpolated based on this calculated progress, Here arrival and departure times align exactly with the train and station positions.

However, when I follow the train path, one route always lags while another is consistently faster. (maybe something to do with the shape coordinates in GTFS file).

 Still exploring different solutions.

**Comment by amith-vp** [comment]
@subins2000

fixed issue #1

Now uses the metro track for active trains. There may be a small visually "unnoticeable" jump from just before/after the station to the station during stops. 

also added two tracks for each direction (track 2 was actually in the shapefile, but I only found out today 😅)
